fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
  resource: "fos_profile.xml"
  prefix: /profil

#fos_user_register:
#  resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#  prefix: /register

fos_user_resetting:
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
  prefix: /reinitialiser-mot-de-passe

fos_user_change_password:
  resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
  prefix: /profil/